# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0

# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_2:
    has_velocity_limits: true
    max_velocity: 1.5707
    has_acceleration_limits: true
    max_acceleration: 0.31414
  joint_6:
    has_velocity_limits: true
    max_velocity: 3.3161
    has_acceleration_limits: true
    max_acceleration: 0.66322
  joint_1:
    has_velocity_limits: true
    max_velocity: 1.7453
    has_acceleration_limits: true
    max_acceleration: 0.34906
  joint_5:
    has_velocity_limits: true
    max_velocity: 2.4435
    has_acceleration_limits: true
    max_acceleration: 0.4887
  joint_3:
    has_velocity_limits: true
    max_velocity: 1.5707
    has_acceleration_limits: true
    max_acceleration: 0.31414
  joint_4:
    has_velocity_limits: true
    max_velocity: 2.9671
    has_acceleration_limits: true
    max_acceleration: 0.59342
  track1:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: true
    max_acceleration: 2.0