controller_list:
  - name: fake_irb6640_controller
    type: $(arg fake_execution_type)
    joints:
      - irb6640_track_1
      - irb6640_joint_1
      - irb6640_joint_2
      - irb6640_joint_3
      - irb6640_joint_4
      - irb6640_joint_5
      - irb6640_joint_6
  - name: fake_irb4400_controller
    type: $(arg fake_execution_type)
    joints:
      - irb4400_joint_1
      - irb4400_joint_2
      - irb4400_joint_3
      - irb4400_joint_4
      - irb4400_joint_5
      - irb4400_joint_6
  - name: fake_dfab_multirobot_controller
    type: $(arg fake_execution_type)
    joints:
      - irb4400_joint_1
      - irb4400_joint_2
      - irb4400_joint_3
      - irb4400_joint_4
      - irb4400_joint_5
      - irb4400_joint_6
      - irb6640_track_1
      - irb6640_joint_1
      - irb6640_joint_2
      - irb6640_joint_3
      - irb6640_joint_4
      - irb6640_joint_5
      - irb6640_joint_6
initial:  # Define initial robot poses per group
  - group: irb6640
    pose: i6640_default
  - group: irb4400
    pose: 4400_default
  - group: dfab_multirobot
    pose: multirobot_default